# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\auntilz\Desktop\ePub\epub.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(489, 417)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(7, 6, 481, 381))
        self.label.setStyleSheet(".QLabel{\n"
"    background-color: rgb(51,51,51);\n"
"    border-radius:3px;\n"
"}")
        self.label.setText("")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(199, 299, 91, 31))
        self.pushButton.setStyleSheet(".QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(30, 146, 141);\n"
"    border-radius:5px;\n"
"\n"
"}\n"
".QPushButton:hover{\n"
"    background-color: rgb(42,208,202);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(397, 16, 15, 15))
        self.pushButton_2.setStyleSheet(".QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(254,96,85);\n"
"    border-radius:7px;\n"
"\n"
"}")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(427, 16, 15, 15))
        self.pushButton_3.setStyleSheet(".QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(248,191,34);\n"
"    border-radius:7px;\n"
"\n"
"}")
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(457, 16, 15, 15))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet(".QPushButton{\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(34,198,52);\n"
"    border-radius:7px;\n"
"\n"
"}")
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(5, 40, 481, 101))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(240, 240, 240);")
        self.label_2.setScaledContents(False)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(129, 345, 231, 20))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_3.setFont(font)
        self.label_3.setStyleSheet(".QLabel{\n"
"color: rgb(103,103,108);\n"
"}\n"
".QLabel:hover{\n"
"color:rgb(255, 255, 255);\n"
"}\n"
"")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(185, 136, 121, 141))
        self.label_4.setStyleSheet(".QLabel{\n"
"    \n"
"    \n"
"    background-image: url(:/1/src/2.png);\n"
"}\n"
".QLabel:hover{\n"
"    background-color: rgb(118,118,122);\n"
"    border-radius:10px;\n"
"    background-image: url(:/1/src/1.png);\n"
"    background-repeat:no-repeat\n"
"}")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(201, 230, 91, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(9, 7, 477, 3))
        self.progressBar.setToolTip("")
        self.progressBar.setStyleSheet("QProgressBar {\n"
"border-radius: 1px;\n"
"text-align: center;\n"
"}\n"
"QProgressBar::chunk {\n"
"background-color:rgb(42,208,202);\n"
"}\n"
"\n"
"")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(20, 340, 31, 31))
        self.pushButton_5.setStyleSheet("QPushButton{\n"
"border-image: url(:/1/src/5.png);\n"
"}")
        self.pushButton_5.setText("")
        self.pushButton_5.setObjectName("pushButton_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 489, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.pushButton_4.clicked.connect(MainWindow.close)
        self.pushButton_2.clicked.connect(MainWindow.showMinimized)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "转化到ePub"))
        self.label_2.setText(_translate("MainWindow", "拖拽文件到此窗口"))
        self.label_3.setText(_translate("MainWindow", "author:Auntilz  |  yareyaredaze (●ˇ∀ˇ●)"))
        self.label_5.setText(_translate("MainWindow", "手动添加"))
        self.progressBar.setFormat(_translate("MainWindow", "%p%"))
import src_rc
